apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-serving-config
  namespace: ml-serving
data:
  MODEL_URI: "models:/telco-churn-model@champion"
  MLFLOW_TRACKING_URI: "http://mlflow.192.168.1.121.nip.io"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-api.192.168.1.121.nip.io"
  AWS_S3_FORCE_PATH_STYLE: "true"