FROM python:3.11-slim

WORKDIR /app

# Evita problemas con logs y buffers
ENV PYTHONUNBUFFERED=1

# Copiamos requirements
COPY serving/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copiamos código
COPY serving /app/serving

# Puerto FastAPI
EXPOSE 8000

# Arranque
CMD ["uvicorn", "serving.app:app", "--host", "0.0.0.0", "--port", "8000"]